DROP TABLE IF EXISTS doc_entries;
DROP TABLE IF EXISTS doc_collections;
DROP TABLE IF EXISTS test_results;
DROP TABLE IF EXISTS artifacts;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS prds;
DROP TABLE IF EXISTS cards;

DROP TYPE IF EXISTS plan_status;
DROP TYPE IF EXISTS doc_status;
DROP TYPE IF EXISTS run_status;
DROP TYPE IF EXISTS agent_type;
DROP TYPE IF EXISTS stage;
