package db

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

var ErrNotOwned = errors.New("draft does not belong to this card")

type Card struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	RepoPath     string    `json:"repoPath"`
	Branch       string    `json:"branch"`
	WorktreePath *string   `json:"worktreePath"`
	Stage        string    `json:"stage"`
	Agent        string    `json:"agent"`
	Status       string    `json:"status"`
	ActivePRDID  string    `json:"activePrdId"`
	ActivePlanID *string   `json:"activePlanId"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type CardStore struct {
	pool *pgxpool.Pool
}

func NewCardStore(pool *pgxpool.Pool) *CardStore {
	return &CardStore{pool: pool}
}

// Create inserts the card plus its first PRD draft ("Draft 1") and marks it
// active, atomically — every card always has an active PRD from creation
// on. prdID is generated by the caller (same id-generation convention used
// throughout this codebase).
func (s *CardStore) Create(ctx context.Context, id, title, repoPath, branch, agent, prdID string) (*Card, error) {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `
		INSERT INTO cards (id, title, repo_path, branch, agent) VALUES ($1, $2, $3, $4, $5)
	`, id, title, repoPath, branch, agent); err != nil {
		return nil, err
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO prds (id, card_id, title, content) VALUES ($1, $2, 'Draft 1', '')
	`, prdID, id); err != nil {
		return nil, err
	}
	row := tx.QueryRow(ctx, `
		UPDATE cards SET active_prd_id = $2, updated_at = now() WHERE id = $1
		RETURNING id, title, repo_path, branch, worktree_path, stage, agent, status, active_prd_id, active_plan_id, created_at, updated_at
	`, id, prdID)
	card, err := scanCard(row)
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return card, nil
}

func (s *CardStore) Get(ctx context.Context, id string) (*Card, error) {
	row := s.pool.QueryRow(ctx, `
		SELECT id, title, repo_path, branch, worktree_path, stage, agent, status, active_prd_id, active_plan_id, created_at, updated_at
		FROM cards WHERE id = $1
	`, id)
	return scanCard(row)
}

func (s *CardStore) List(ctx context.Context) ([]*Card, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id, title, repo_path, branch, worktree_path, stage, agent, status, active_prd_id, active_plan_id, created_at, updated_at
		FROM cards ORDER BY updated_at DESC
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	cards := []*Card{}
	for rows.Next() {
		c, err := scanCard(rows)
		if err != nil {
			return nil, err
		}
		cards = append(cards, c)
	}
	return cards, rows.Err()
}

func (s *CardStore) Update(ctx context.Context, id, title, repoPath, agent string) (*Card, error) {
	row := s.pool.QueryRow(ctx, `
		UPDATE cards SET title = $2, repo_path = $3, agent = $4, updated_at = now()
		WHERE id = $1
		RETURNING id, title, repo_path, branch, worktree_path, stage, agent, status, active_prd_id, active_plan_id, created_at, updated_at
	`, id, title, repoPath, agent)
	return scanCard(row)
}

func (s *CardStore) UpdateStage(ctx context.Context, id, stage, status string) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE cards SET stage = $2, status = $3, updated_at = now() WHERE id = $1
	`, id, stage, status)
	return err
}

func (s *CardStore) SetWorktreePath(ctx context.Context, id, worktreePath string) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE cards SET worktree_path = $2, updated_at = now() WHERE id = $1
	`, id, worktreePath)
	return err
}

func (s *CardStore) SetBranch(ctx context.Context, id, branch string) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE cards SET branch = $2, updated_at = now() WHERE id = $1
	`, id, branch)
	return err
}

// SetActivePRD/SetActivePlan verify ownership at the SQL level (the FK on
// active_prd_id/active_plan_id only checks the row exists, not that it
// belongs to this card) — zero rows affected means either the card or the
// draft-ownership check failed, surfaced as ErrNotOwned.
func (s *CardStore) SetActivePRD(ctx context.Context, cardID, prdID string) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE cards SET active_prd_id = $2, updated_at = now()
		WHERE id = $1 AND EXISTS (SELECT 1 FROM prds WHERE id = $2 AND card_id = $1)
	`, cardID, prdID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotOwned
	}
	return nil
}

func (s *CardStore) SetActivePlan(ctx context.Context, cardID, rootID string) error {
	tag, err := s.pool.Exec(ctx, `
		UPDATE cards SET active_plan_id = $2, updated_at = now()
		WHERE id = $1 AND EXISTS (SELECT 1 FROM plans WHERE root_id = $2 AND card_id = $1)
	`, cardID, rootID)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotOwned
	}
	return nil
}

type rowScanner interface {
	Scan(dest ...any) error
}

func scanCard(row rowScanner) (*Card, error) {
	var c Card
	err := row.Scan(&c.ID, &c.Title, &c.RepoPath, &c.Branch, &c.WorktreePath,
		&c.Stage, &c.Agent, &c.Status, &c.ActivePRDID, &c.ActivePlanID, &c.CreatedAt, &c.UpdatedAt)
	if err != nil {
		return nil, err
	}
	return &c, nil
}
